const mongoose = require("mongoose");
require("dotenv").config();

const Job = require("./models/Job");

const jobs = [
  {
    title: "Software Engineer",
    company: "Google",
    location: "Bangalore",
    salary: "₹25 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    description: "Develop scalable web applications using modern technologies.",
    skills: "JavaScript, React, Node.js",
    category: "Software Development",
    companyLogo: "",
  },
  {
    title: "Frontend Developer",
    company: "Microsoft",
    location: "Hyderabad",
    salary: "₹18 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    description: "Build responsive React applications using React.js.",
    skills: "React, HTML, CSS, JavaScript",
    category: "Frontend",
    companyLogo: "",
  },
  {
    title: "Data Analyst",
    company: "Amazon",
    location: "Chennai",
    salary: "₹15 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    description: "Analyze business data and create insightful reports.",
    skills: "SQL, Excel, Power BI",
    category: "Data Analytics",
    companyLogo: "",
  },
  {
    title: "Power BI Developer",
    company: "Infosys",
    location: "Hyderabad",
    salary: "₹8 LPA",
    experience: "1-2 Years",
    type: "Full Time",
    description: "Develop interactive Power BI dashboards.",
    skills: "Power BI, DAX, SQL",
    category: "Business Intelligence",
    companyLogo: "",
  },
  {
    title: "React Developer",
    company: "TCS",
    location: "Pune",
    salary: "₹7 LPA",
    experience: "1-2 Years",
    type: "Full Time",
    description: "Develop modern React web applications.",
    skills: "React, Redux, JavaScript",
    category: "Frontend",
    companyLogo: "",
  },
    {
    title: "Java Developer",
    company: "Accenture",
    location: "Bangalore",
    salary: "₹10 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    description: "Develop enterprise Java applications using Spring Boot.",
    skills: "Java, Spring Boot, SQL",
    category: "Backend",
    companyLogo: "",
  },
  {
    title: "Business Analyst",
    company: "Deloitte",
    location: "Hyderabad",
    salary: "₹9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    description: "Analyze business requirements and prepare reports.",
    skills: "Excel, SQL, Communication",
    category: "Business",
    companyLogo: "",
  },
  {
    title: "Full Stack Developer",
    company: "Capgemini",
    location: "Chennai",
    salary: "₹8 LPA",
    experience: "2 Years",
    type: "Full Time",
    description: "Develop MERN stack web applications.",
    skills: "MongoDB, Express, React, Node.js",
    category: "Full Stack",
    companyLogo: "",
  },
  {
    title: "Python Developer",
    company: "Wipro",
    location: "Hyderabad",
    salary: "₹7.5 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    description: "Develop backend APIs using Python and Django.",
    skills: "Python, Django, REST API",
    category: "Backend",
    companyLogo: "",
  },
  {
    title: "QA Engineer",
    company: "Cognizant",
    location: "Bangalore",
    salary: "₹6.5 LPA",
    experience: "1-2 Years",
    type: "Full Time",
    description: "Perform manual and automation software testing.",
    skills: "Selenium, Manual Testing",
    category: "Testing",
    companyLogo: "",
  },
    {
    title: "Cloud Engineer",
    company: "IBM",
    location: "Pune",
    salary: "₹12 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    description: "Manage cloud infrastructure and deployment pipelines.",
    skills: "AWS, Azure, Docker",
    category: "Cloud",
    companyLogo: "",
  },
  {
    title: "SQL Developer",
    company: "Oracle",
    location: "Hyderabad",
    salary: "₹11 LPA",
    experience: "2 Years",
    type: "Full Time",
    description: "Develop SQL queries, stored procedures and optimize databases.",
    skills: "SQL, PL/SQL",
    category: "Database",
    companyLogo: "",
  },
  {
    title: "Backend Developer",
    company: "Zoho",
    location: "Chennai",
    salary: "₹9 LPA",
    experience: "2 Years",
    type: "Full Time",
    description: "Build scalable backend services and REST APIs.",
    skills: "Node.js, Express, MongoDB",
    category: "Backend",
    companyLogo: "",
  },
  {
    title: "UI/UX Designer",
    company: "Adobe",
    location: "Bangalore",
    salary: "₹16 LPA",
    experience: "2 Years",
    type: "Full Time",
    description: "Design intuitive and modern user interfaces.",
    skills: "Figma, Adobe XD",
    category: "Design",
    companyLogo: "",
  },
  {
    title: "Android Developer",
    company: "Flipkart",
    location: "Bangalore",
    salary: "₹13 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    description: "Develop and maintain Android applications.",
    skills: "Kotlin, Android Studio",
    category: "Mobile",
    companyLogo: "",
  },
    {
    title: "DevOps Engineer",
    company: "Tech Mahindra",
    location: "Hyderabad",
    salary: "₹12 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    description: "Manage CI/CD pipelines and cloud deployments.",
    skills: "Docker, Kubernetes, Jenkins",
    category: "DevOps",
    companyLogo: "",
  },
  {
    title: "Machine Learning Engineer",
    company: "NVIDIA",
    location: "Bangalore",
    salary: "₹22 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    description: "Build machine learning models for real-world applications.",
    skills: "Python, TensorFlow, Scikit-learn",
    category: "Artificial Intelligence",
    companyLogo: "",
  },
  {
    title: "Cyber Security Analyst",
    company: "HCL Technologies",
    location: "Noida",
    salary: "₹10 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    description: "Monitor systems and protect against cyber threats.",
    skills: "Network Security, SIEM, Ethical Hacking",
    category: "Cyber Security",
    companyLogo: "",
  },
  {
    title: "Data Scientist",
    company: "Paytm",
    location: "Noida",
    salary: "₹18 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    description: "Analyze large datasets and build predictive models.",
    skills: "Python, SQL, Machine Learning",
    category: "Data Science",
    companyLogo: "",
  },
  {
    title: "MERN Stack Developer",
    company: "StartupHub",
    location: "Remote",
    salary: "₹9 LPA",
    experience: "0-2 Years",
    type: "Remote",
    description: "Build full-stack applications using the MERN stack.",
    skills: "MongoDB, Express.js, React, Node.js",
    category: "Full Stack",
    companyLogo: "",
  },
];

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    console.log("✅ MongoDB Connected");

    await Job.deleteMany({});
    console.log("🗑 Existing jobs deleted");

    await Job.insertMany(jobs);
    console.log(`✅ ${jobs.length} jobs inserted successfully!`);

    mongoose.connection.close();
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    mongoose.connection.close();
  }
}

seedDatabase();